application: exeter-math
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /create_team
  script: routes.application
- url: /edit_info
  script: routes.application
- url: /register
  script: routes.application
- url: /login
  script: routes.application
- url: /logout
  script: routes.application
- url: /forgot
  script: routes.application
- url: /reset
  script: routes.application
- url: /reset/(.+)
  script: routes.application
- url: /cleanup
  script: routes.application
  login: admin
- url: /bower_components
  static_dir: bower_components
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
  application_readable: true
- url: /
  static_files: static/index.html
  upload: static/index.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- mail
- warmup
