application: exeter-math
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /create_team
  script: routes.application
- url: /edit_info
  script: routes.application
- url: /list
  script: routes.application
- url: /list_all
  script: routes.application
- url: /register
  script: routes.application
- url: /login
  script: routes.application
  secure: always
- url: /logout
  script: routes.application
- url: /forgot
  script: routes.application
- url: /reset
  script: routes.application
- url: /reset/(.+)
  static_files: static/reset.html
  upload: static/reset.html
- url: /admin_list
  script: routes.application
  login: admin
- url: /cleanup
  script: routes.application
  login: admin
- url: /add_legacy
  script: routes.application
- url: /add_legacy_team
  script: routes.application
- url: /send_emails
  script: routes.application
  login: admin
- url: /grade
  script: routes.application
- url: /check
  script: routes.application
- url: /admin.html
  static_files: static/admin.html
  upload: static/admin.html
  login: admin
  secure: always
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

inbound_services:
- mail
- warmup

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?node_modules$
- ^(.*/)?src$
